### ISSUE TITLE
Issue installing FLAME-related software on Mac

### ISSUE THREAD

**Issue by buchmog** [FLAME-HPC/xparser#10]
Hello, I'm working on an abm project using FLAME, but am unable to get the required programmes to work on Mac OS. Any help directing me to a comprehensive guide for installing them or their Mac equivalents would be much appreciated.

**Comment by svdhoog** [comment]
By Mac OS I assume you mean Mac OS X? Since Mac OS X is a POSIX-certified system and uses some code from the FreeBSD kernel, I assume it should be feasible to install FLAME from the terminal.
Can you send us the steps you took, and where it goes wrong, including the terminal output of the relevant step?

**Comment by buchmog** [comment]
Hi, thanks for your reply. I've since found a way to install FLAME, and you're right, through Terminal.
